import type { Metadata } from "next";
import SideNav from "./Components/SideBar";
import NavBar from "@/app/Components/NavBar";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import {authOptions} from "@/app/utils/authOptions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function StudentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  if (!session){
    redirect('/login')
  }
  const userType =session?.userType
  return (
    <>
      <div className="w-screen h-screen flex flex-col overflow-hidden">
          <div className="flex flex-row">
            <div className="h-screen px-4 w-[15vw] bg-sky-400">
              <SideNav></SideNav>
            </div>
            <div className="w-full h-full">{children}</div>
          </div>
      </div>
    </>
  );
}
